### ISSUE TITLE
Compatibility with desuarchive?

### ISSUE THREAD

**Issue by randoomdude** [mycropen/x-links#2]
I'm trying to reach out to any programmer working on x-links since the old one hasn't responded to any issues in years, but if you can get x-links to work on desuarchive with proper thumbnails unlike now where the links have no image and lose like 90% of the point of the extension, if you could find a way to fix it that would be awesom
![image](https://user-images.githubusercontent.com/6027132/228391858-7c52ff20-b71f-474e-a00e-b168d629acca.png)
e

**Comment by mycropen** [comment]
The issue seems to be with desuarchive's content security policy and not X-Links. I don't get this problem on the latest Firefox with Tampermonkey, but on Chrome with Tampermonkey I had to use this [workaround](https://github.com/Tampermonkey/tampermonkey/issues/952#issuecomment-638373937) to have the images appear. Can you try if this works for you first?

**Comment by randoomdude** [comment]
didn't see your comment originally but finally did and yes it solved my issue, belated but thanks a lot for your help
